# Generated by Django 4.1 on 2022-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField()),
                ('username', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
